name: Build new packages
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    container: archlinux:base-devel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add pacman repo
        run: |
            cat<<EOF >> /etc/pacman.conf
            [multilib]
            Include = /etc/pacman.d/mirrorlist
            [crepo]
            SigLevel = Optional TrustAll DatabaseOptional
            Server = https://babarulea.000webhostapp.com/arch/
            EOF
      - run: |
          pacman -Sy rclone paru --noconfirm
          useradd -m user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      - run: su user -c ./build.sh
      - name: Setup rclone
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          rclone ls ff:/public_html
      - run: |
          cd /tmp/crepo
          ls
          rclone copy . ff:/public_html/arch --progress --copy-links

