name: Build with wlroots-git
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    container: archlinux:base-devel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          pacman -Sy rclone --noconfirm
          useradd -m user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          # cd tlstunnel
          # chown -R user .
          # # su user -c "makepkg -s --noconfirm"
          # curl --ssl-reqd -k -u ${{ secrets.FTP_AUTH }} -T tlstunnel*.tar.zst ftp://ftp.epizy.com/htdocs/arch/ 
      - name: Rclone
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          rclone ls ff:/public_html
      - run: ./build.sh
      - run: |
          cd /tmp/crepo
          ls
          rclone sync . ff:/public_html/arch --progress --copy-links

